hexlet_django_blog/articles/urls.py
from django.urls import path
from python_django_blog.articles import views

app_name = 'articles'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.ArticleCreate.as_view(), name='create'),
    path('<int:pk>/delete/', views.ArticleDelete.as_view(), name='delete'),
    path('<int:pk>/update/', views.ArticleUpdate.as_view(), name='update'),
    path('<int:pk>/', views.ArticleDetail.as_view(), name='detail'),
]

hexlet_django_blog/urls.py
from django.urls import include, path
from python_django_blog import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='root'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('articles/', include('python_django_blog.articles.urls')),
]

hexlet_django_blog/articles/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Article(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)
    description = models.TextField(_('description'))
    created_at = models.DateTimeField(_('created date'), default=timezone.now)

    def get_absolute_url(self):
        return reverse('articles:index')

    def __str__(self):
        return self.name

hexlet_django_blog/articles/forms.py
from django.forms import ModelForm
from python_django_blog.articles.models import Article


class ArticleForm(ModelForm):

    class Meta:
        model = Article
        fields = ['name', 'description']

hexlet_django_blog/articles/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from python_django_blog.articles.models import Article
from python_django_blog.articles.forms import ArticleForm


class IndexView(ListView):
    model = Article
    template_name = 'articles/index.html'


class ArticleCreate(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'articles/create.html'


class ArticleUpdate(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'articles/update.html'


class ArticleDelete(DeleteView):
    model = Article
    success_url = reverse_lazy('articles:index')
    template_name = 'articles/delete.html'


class ArticleDetail(DetailView):
    model = Article
    template_name = 'articles/detail.html'

hexlet_django_blog/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'


class AboutView(TemplateView):
    template_name = 'about.html'

hexlet_django_blog/templates/about.html
{% extends 'layouts/application.html' %}
{% load i18n %}

{% block header %}
{% translate "About the blog" %}
{% endblock %}

{% block content %}
{% translate "Experimenting with Django on Hexlet" %}
{% endblock %}

hexlet_django_blog/templates/articles/create.html
{% extends 'layouts/form.html' %}
{% load i18n %}

{% block header %}
{% translate "Create article" %}
{% endblock %}

{% block button_value %}{% translate "Create" %}{% endblock %}

hexlet_django_blog/templates/articles/delete.html
{% extends 'layouts/confirm_delete.html' %}
{% load i18n %}

{% block header %}
{% translate "Delete article" %}
{% endblock %}

hexlet_django_blog/templates/articles/detail.html
{% extends 'layouts/application.html' %}
{% load i18n %}

{% block header %}
{% translate "Show article" %}
{% endblock %}

{% block content %}
<div class="card">
  <div class="card-header bg-secondary text-white">
    <h2>{{ article.name }}</h2>
  </div>
  <div class="card-body bg-light">
    <p>{{ article.description }}</p>
  </div>
</div>
{% endblock %}

hexlet_django_blog/templates/articles/index.html
{% extends 'layouts/application.html' %}
{% load i18n %}

{% block header %}
{% translate "List of Articles" %}
{% endblock %}

{% block content %}
<a class="nav-link" href="{% url 'articles:create' %}">{% translate "Create article" %}</a>
<table class="table table-striped">
  <thead>
    <tr>
      <th>{% translate "id"|upper %}</th>
      <th>{% translate "name"|capfirst %}</th>
      <th>{% translate "created date"|capfirst %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for article in article_list %}
      <tr>
        <td>{{ article.id }}</td>
        <td>
          <a href="{% url 'articles:detail' article.id %}">{{ article.name }}</a>
        </td>
        <td>{{ article.created_at|date:"d.m.Y H:i" }}</td>
        <td>
          <a href="{% url 'articles:update' article.id %}">{% translate "Update" %}</a>
          <br>
          <a href="{% url 'articles:delete' article.id %}">{% translate "Delete" %}</a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

hexlet_django_blog/templates/articles/update.html
{% extends 'layouts/form.html' %}
{% load i18n %}

{% block header %}
{% translate "Update article" %}
{% endblock %}

{% block button_value %}{% translate "Update" %}{% endblock %}

hexlet_django_blog/templates/index.html
{% extends 'layouts/application.html' %}
{% load i18n %}

{% block header %}
{% translate "Python Django Blog" %}
{% endblock %}

hexlet_django_blog/templates/layouts/application.html
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% translate "Django" %}</title>
    {% bootstrap_css %}
  </head>
  <body class="bg-light">
    <div class="container mt-4">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'root' %}">{% translate "Home" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">{% translate "About" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'articles:index' %}">{% translate "Articles" %}</a>
        </li>
      </ul>
    </div>
    <div class="container mt-4">
      <h1>
        {% block header %}
        {% endblock %}
      </h1>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

hexlet_django_blog/templates/layouts/confirm_delete.html
{% extends 'layouts/application.html' %}
{% load i18n %}

{% block content %}
<p>{% translate "Are you sure you want to delete" %} {{ object }}?</p>
<form method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="{% translate 'Yes, delete' %}">
</form>
{% endblock %}

hexlet_django_blog/templates/layouts/form.html
{% extends 'layouts/application.html' %}
{% load bootstrap4 %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <input class="btn btn-primary" type="submit" value="{% block button_value %}{% endblock %}">
  {% endbuttons %}
</form>
{% endblock %}